-- to run in terminal
-- 1. Create database with sqlite3 dbname.db
-- 2. Run this file with .read create_tbl.sql

-- create FILGRUPPER tabel
CREATE TABLE `FILGRUPPER` (
  `ID`            INTEGER NOT NULL,
  `FILGRUPPE`     TEXT NOT NULL,
  `AAR`           INTEGER,
  `GEO`           INTEGER,
  `ALDER`         INTEGER,
  `ALDER_ALLE`    TEXT,
  `KJONN`         INTEGER,
  `UTDANN`        INTEGER,
  `SIVST`         INTEGER,
  `LANDBAK`       INTEGER,
  `TAB1`          TEXT,
  `TAB2`          TEXT,
  `TAB3`          TEXT,
  `B_STARTAAR`    INTEGER,
  `SY_PAA_FILGR`  INTEGER,
  `RSYNT_SYPAA`   INTEGER,
  `ValErAarsSnitt` INTEGER,
  `VAL1navn`      TEXT,
  `VAL1sumbar`    INTEGER,
  `VAL1miss`      TEXT,
  `VAL2navn`      TEXT,
  `VAL2sumbar`    INTEGER,
  `VAL2miss`      TEXT,
  `VAL3navn`      TEXT,
  `VAL3sumbar`    INTEGER,
  `VAL3miss`      TEXT,
  `RSYNT2`        INTEGER,
  `PRODDATO`      TEXT,
  `VERSJONFRA`    TEXT,
  `VERSJONTIL`    TEXT,
  `FILTER1`       INTEGER,
  `FILTER2`       INTEGER,
  `FILTER3`       INTEGER,
  `RSYNT_PRE_FGLAGRING` TEXT,
  `ANM_RSYNT`     TEXT,
  `hgh`           REAL,
  PRIMARY KEY (ID, FILGRUPPE)
);


CREATE TABLE "INNLESING" (
        "ID"            INTEGER,
        "FILGRUPPE"	TEXT,
        "DELID"         TEXT,
        "BRUK"          INTEGER,
        "VERSJONFRA"	TEXT,
        "VERSJONTIL"	TEXT,
        "FORMATgml"	TEXT,
        "INNLESARG"	TEXT,
        "MANHEADER"	TEXT,
        "MULTIHEAD"	TEXT,
        "KASTKOLS"	TEXT,
        "UNDERTABLOK"	TEXT,
        "FYLLTAB"	TEXT,
        "RESHAPEid"	TEXT,
        "RESHAPEmeas"	TEXT,
        "RESHAPEvar"	TEXT,
        "RESHAPEval"	TEXT,
        "AGGERGER_DF"	INTEGER,
        "RSYNT1"	TEXT,
        "RSYNT2"	TEXT,
        "FEILRAPPORT"	TEXT,
        "GEO"           TEXT,
        "GEOd2"         TEXT,
        "GRUNNKRETS"	INTEGER,
        "TKNR"          INTEGER,
        "SONER"         TEXT,
        "AAR"           TEXT,
        "KJONN"         TEXT,
        "ALDER"         TEXT,
        "UTDANN"	TEXT,
        "SIVST"         TEXT,
        "LANDBAK"	TEXT,
        "TAB1"          TEXT,
        "TAB2"          TEXT,
        "TAB3"          TEXT,
        "VAL1"          TEXT,
        "VAL2"          TEXT,
        "VAL3"          TEXT,
        "ALDERkb"	TEXT,
        "KJONNkb"	TEXT,
        "TAB1kb"	TEXT,
        "TAB2kb"	TEXT,
        "TAB3kb"	TEXT,
        "KOMMENTAR"	TEXT,
        "RAPPORT2"	INTEGER,
        "TID"           REAL,
        "PROSESSDATO"	TEXT,
        "SKALA_VAL1"	INTEGER,
        "SKALA_VAL2"	INTEGER,
        "SKALA_VAL3"	INTEGER
);


CREATE TABLE "ORIGINALFILER" (
        "FILID"         INTEGER,
        "LEVERANDØR"	TEXT,
        "FILNAVN"	TEXT,
        "FORMAT"	TEXT,
        "LEVERANSEAAR"	INTEGER,
        "PERIODE"	INTEGER,
        "DEFAAR"	INTEGER,
        "TYPE"          INTEGER,
        "DATO_MOTTAK"	TEXT,
        "FORVENTET_MOTTAK"	TEXT,
        "IBRUKFRA"	TEXT,
        "IBRUKTIL"	TEXT,
        "AVSENDER"	INTEGER,
        "ANSVAR_LEVERANSE"	INTEGER,
        "MOTTAKER"	INTEGER,
        "MODUS"         INTEGER,
        "STATUS_HOS_LEVERANDOR"	INTEGER,
        "KOMMENTAR"	TEXT
);
